### ISSUE TITLE
BYU agent installed, not executing

### ISSUE THREAD

**Issue by joprysko1** [danielricks/IEEE-CIG-2016-Text-based-Adventure-AI-Competition-Winning-Agent#1]
After I installed BYU-Agent, Autoplay is still only using AgentBaseClass, not the BYU-Agent.  Not sure if there is something else I need to specify when running autoplay.

**Comment by danielricks** [comment]
Yeah, autoplay uses whatever agent is specified in the autoplay.py file. You'll have to swap out which agent autoplay is currently pointing to. 

In autoplay.py, at the top of the file you'll see 'import agents.agentBaseClass as ac'. Swap out agentBaseClass with 'byuAgent'.

Then down below (line 66 ish), you'll see a command that says 'a = ac.AgentBaseClass(initial_epsilon, training_cycles)'. Swap out 'AgentBaseClass' with 'byuAgent'.

That should do it.
